name: music_life
description: A music practice companion app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  shared_preferences: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  record: ^5.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
