name: music_life
description: A music practice companion app.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  intl: any
  shared_preferences: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  record: ^6.2.0
  url_launcher: ^6.3.1
  go_router: ^16.2.0
  file_selector: ^1.0.3
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
